### PR TITLE
Add tomlplusplus as dependency

### LINKED ISSUE #14: Enable the compilation of the TOMLImplementation of the parameter handler
### Comment:

It would be nice to have the toml implementation compiled within the receipt. The only new dependency we need to add is `tomlplusplus` which is already packaged in conda-forge https://github.com/conda-forge/tomlplusplus-feedstock

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This closes #14

### CODE REVIEW

**Comment by GiulioRomualdi** [comment]
@conda-forge-admin, please rerender

**Comment by GiulioRomualdi** [comment]
@conda-forge-admin, please rerender

**Review by traversaro — APPROVED** [review]

**Comment by h-vetinari** [comment]
@conda-forge/bipedal-locomotion-framework 
Someone managed to start the job for the merge of this PR 12(!) times on main, which - given 12 jobs and an average runtime of an hour - is causing a lot of other builds in conda-forge to have to wait for resources.

Could someone please cancel 11 out of those 12 jobs?

CC @conda-forge/core

**Comment by traversaro** [comment]
Hi @h-veterinari, sorry for the trouble and thanks for finding this, probably we did something wrong related to https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/issues/16 . And thanks @beckermr for deleting them!

**Comment by h-vetinari** [comment]
> I think I cancelled them. Thanks for finding this! I was looking but couldn't.

I think it was @jakirkham who once referenced the conda-forge-wide [dashboards](https://dev.azure.com/conda-forge/feedstock-builds/_build?view=runs) that are available in azure (which I hadn't seen before that either).

**Comment by traversaro** [comment]
By the way, one of the reason those builds were so problematic is due to a workaround we added in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/10 . Hopefully we can remove that workaround now, see https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/17 .

**Pull request merged**
