### PR TITLE
Enable PCL dependency

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
There is the usual mysterious problem in Python bindings compilation:
~~~
    conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("libbipedal-locomotion-framework==0.15.0=he403c79_2"), MatchSpec("idyntree[version='>=9.1.0,<10.0a0']")}
    Encountered problems while solving:
      - package libbipedal-locomotion-framework-0.15.0-he403c79_2 requires idyntree >=9.1.0,<10.0a0, but none of the providers can be installed
    
    Could not solve for environment specs
    The following packages are incompatible
    ├─ idyntree 10.0.0.* py39h2b24f1d_1 is requested and can be installed;
    └─ libbipedal-locomotion-framework 0.15.0.* he403c79_2 is not installable because it requires
       └─ idyntree >=9.1.0,<10.0a0 , which conflicts with any installable versions previously reported.
~~~
let's see if we can solve this with https://github.com/conda-forge/libunicycle-footstep-planner-feedstock/pull/11 .

**Comment by traversaro** [comment]
New error:
~~~
2023-11-09T15:03:08.1679271Z     conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("casadi[version='>=3.6.3,<3.7.0a0']"), MatchSpec("libbipedal-locomotion-framework==0.15.0=he403c79_2")}
2023-11-09T15:03:08.1680843Z     Encountered problems while solving:
2023-11-09T15:03:08.1681968Z       - package libbipedal-locomotion-framework-0.15.0-he403c79_2 requires casadi >=3.6.3,<3.7.0a0, but none of the providers can be installed
2023-11-09T15:03:08.1683390Z     
2023-11-09T15:03:08.1683716Z     Could not solve for environment specs
2023-11-09T15:03:08.1684185Z     The following packages are incompatible
2023-11-09T15:03:08.1685079Z     ├─ ipopt 3.14.13.* he6d3896_0 is requested and can be installed;
2023-11-09T15:03:08.1686119Z     └─ libbipedal-locomotion-framework 0.15.0.* he403c79_2 is not installable because it requires
2023-11-09T15:03:08.1687400Z        └─ casadi >=3.6.3,<3.7.0a0 , which requires
2023-11-09T15:03:08.1688361Z           └─ ipopt >=3.14.12,<3.14.13.0a0 , which conflicts with any installable versions previously reported.
~~~

**Comment by traversaro** [comment]
> New error:
> 
> ```
> 2023-11-09T15:03:08.1679271Z     conda_libmamba_solver.conda_build_exceptions.ExplainedDependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {MatchSpec("casadi[version='>=3.6.3,<3.7.0a0']"), MatchSpec("libbipedal-locomotion-framework==0.15.0=he403c79_2")}
> 2023-11-09T15:03:08.1680843Z     Encountered problems while solving:
> 2023-11-09T15:03:08.1681968Z       - package libbipedal-locomotion-framework-0.15.0-he403c79_2 requires casadi >=3.6.3,<3.7.0a0, but none of the providers can be installed
> 2023-11-09T15:03:08.1683390Z     
> 2023-11-09T15:03:08.1683716Z     Could not solve for environment specs
> 2023-11-09T15:03:08.1684185Z     The following packages are incompatible
> 2023-11-09T15:03:08.1685079Z     ├─ ipopt 3.14.13.* he6d3896_0 is requested and can be installed;
> 2023-11-09T15:03:08.1686119Z     └─ libbipedal-locomotion-framework 0.15.0.* he403c79_2 is not installable because it requires
> 2023-11-09T15:03:08.1687400Z        └─ casadi >=3.6.3,<3.7.0a0 , which requires
> 2023-11-09T15:03:08.1688361Z           └─ ipopt >=3.14.12,<3.14.13.0a0 , which conflicts with any installable versions previously reported.
> ```

I tried as workaround to add casadi also to the python bindings. However, I am not understanding what is going on, but probably is related to the migration started in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5132 .

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
New error:
~~~
2023-11-09T15:56:33.2723478Z     ├─ ffmpeg 6.0.0.* gpl_h334edf3_105 is requested and can be installed;
2023-11-09T15:56:33.2724406Z     ├─ hdf5 1.14.2.* nompi_h4f84152_100 is requested and can be installed;
2023-11-09T15:56:33.2725491Z     ├─ libbipedal-locomotion-framework 0.15.0.* he403c79_2 is installable and it requires
2023-11-09T15:56:33.2726504Z     │  └─ pcl >=1.13.1,<1.13.2.0a0  with the potential options
2023-11-09T15:56:33.2727171Z     │     ├─ pcl 1.13.1 would require
2023-11-09T15:56:33.2727851Z     │     │  └─ boost-cpp >=1.78.0,<1.78.1.0a0 , which can be installed;
2023-11-09T15:56:33.2728551Z     │     ├─ pcl 1.13.1 would require
2023-11-09T15:56:33.2729225Z     │     │  └─ vtk-base >=9.2.6,<9.2.7.0a0  with the potential options
2023-11-09T15:56:33.2729938Z     │     │     ├─ vtk-base 9.2.6 would require
2023-11-09T15:56:33.2730635Z     │     │     │  └─ pugixml >=1.13,<1.14.0a0 , which can be installed;
2023-11-09T15:56:33.2731308Z     │     │     ├─ vtk-base 9.2.6 would require
2023-11-09T15:56:33.2732044Z     │     │     │  └─ libjpeg-turbo >=2.1.5.1,<3.0a0 , which can be installed;
2023-11-09T15:56:33.2732766Z     │     │     ├─ vtk-base 9.2.6 would require
2023-11-09T15:56:33.2733746Z     │     │     │  └─ hdf5 >=1.14.0,<1.14.1.0a0 , which conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2734695Z     │     │     └─ vtk-base 9.2.6 would require
2023-11-09T15:56:33.2736939Z     │     │        └─ hdf5 >=1.14.1,<1.14.2.0a0 , which conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2738246Z     │     └─ pcl 1.13.1 would require
2023-11-09T15:56:33.2741131Z     │        └─ vtk >=9.2.6,<9.2.7.0a0  with the potential options
2023-11-09T15:56:33.2741932Z     │           ├─ vtk 9.2.6 would require
2023-11-09T15:56:33.2742859Z     │           │  ├─ ffmpeg >=5.1.2,<6.0a0 , which conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2744343Z     │           │  └─ vtk-io-ffmpeg [9.2.6 egl_py310h1234567_3|9.2.6 egl_py310h1234567_4|...|9.2.6 qt_py39h1234567_208], which requires
2023-11-09T15:56:33.2745784Z     │           │     └─ ffmpeg >=5.1.2,<6.0a0 , which conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2746686Z     │           ├─ vtk 9.2.6 would require
2023-11-09T15:56:33.2748049Z     │           │  └─ vtk-base [9.2.6 egl_py310h1234567_10|9.2.6 egl_py310h1234567_8|...|9.2.6 qt_py39h1234567_210], which cannot be installed (as previously explained);
2023-11-09T15:56:33.2749380Z     │           ├─ vtk 9.2.6 would require
2023-11-09T15:56:33.2750709Z     │           │  └─ vtk-base [9.2.6 egl_py310h1234567_11|9.2.6 egl_py310h1234567_12|...|9.2.6 qt_py39h1234567_216], which can be installed (as previously explained);
2023-11-09T15:56:33.2751963Z     │           ├─ vtk 9.2.6 would require
2023-11-09T15:56:33.2753312Z     │           │  └─ vtk-base [9.2.6 egl_py310h1234567_17|9.2.6 egl_py310h1234567_18|...|9.2.6 qt_py39h1234567_218], which can be installed (as previously explained);
2023-11-09T15:56:33.2754813Z     │           └─ vtk 9.2.6 would require
2023-11-09T15:56:33.2756218Z     │              └─ vtk-base [9.2.6 egl_py311h1234567_6|9.2.6 egl_py311h1234567_7|...|9.2.6 qt_py39h1234567_205], which cannot be installed (as previously explained);
2023-11-09T15:56:33.2757649Z     ├─ libboost 1.82.0.* h6fcfa73_6 is not installable because it requires
2023-11-09T15:56:33.2758735Z     │  └─ boost-cpp 1.82.0* , which conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2760254Z     ├─ libjpeg-turbo 3.0.0.* hd590300_1 is not installable because it conflicts with any installable versions previously reported;
2023-11-09T15:56:33.2761929Z     └─ pugixml 1.14.* h59595ed_0 is not installable because it conflicts with any installable versions previously reported.
~~~

No idea why it wants to install such new version of libboost or pugixml, let's add it as dependencies as a workaround.

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
New error, great:  

~~~
bindings named PlannersBindings in BipedalLocomotionFrameworkBindings.
2023-11-09T18:34:08.1269768Z -- Added files for bindings named UnicycleBindings in BipedalLocomotionFrameworkBindings.
2023-11-09T18:34:08.1270844Z CMake Error at python/RobotInterface/CMakeLists.txt:30 (FetchContent_Declare):
2023-11-09T18:34:08.1271680Z   Unknown CMake command "FetchContent_Declare".
2023-11-09T18:34:08.1272139Z 
2023-11-09T18:34:08.1272331Z 
2023-11-09T18:34:08.1273136Z -- Added files for bindings named RobotInterfaceBindings in BipedalLocomotionFrameworkBindings.
2023-11-09T18:34:08.1274050Z -- Configuring incomplete, errors occurred!
2023-11-09T18:34:08.1274492Z 
2023-11-09T18:34:08.1274781Z # 
~~~

**Comment by traversaro** [comment]
Fixed by backporting https://github.com/ami-iit/bipedal-locomotion-framework/pull/757 in the PR, see https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/42/commits/0b13f14a704b6e35467647a15667946c71e05726 and https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/42/commits/59004b3a5cb74e86d8c475b57ce36c807237dc79 .

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
@traversaro do you think we can merge it?

**Comment by traversaro** [comment]
> @traversaro do you think we can merge it?

Yes!

**Pull request merged**
