### PR TITLE
Add onnxruntime-cpp dependency and verify that required Python modules are installed

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by GiulioRomualdi** [comment]
🤔 It's not able to load onnxruntime in the tests https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=861052&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=8909

**Comment by traversaro** [comment]
> 🤔 It's not able to load onnxruntime in the tests https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=861052&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=8909

Ah, I think it is the problem described in https://github.com/conda-forge/onnxruntime-feedstock/pull/78 . The discussion there kind of went stale, but I think for now we can just pin onnxruntime-cpp and manually add a run exports.

**Comment by traversaro** [comment]
> > 🤔 It's not able to load onnxruntime in the tests https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=861052&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=8909
> 
> Ah, I think it is the problem described in [conda-forge/onnxruntime-feedstock#78](https://github.com/conda-forge/onnxruntime-feedstock/pull/78) . The discussion there kind of went stale, but I think for now we can just pin onnxruntime-cpp and manually add a run exports.

Ok, I proposed the proper fix in https://github.com/conda-forge/onnxruntime-feedstock/pull/102 .

**Comment by traversaro** [comment]
Interestingly, the Windows failure is:
~~~
-------------------------------------------------------------------------------
QP-IK [Distance and Gravity tasks Unconstrained]
-------------------------------------------------------------------------------
D:\bld\bipedal-locomotion-framework_1705663992921\work\src\IK\tests\QPInverseKinematicsTest.cpp(858)
...............................................................................

D:\bld\bipedal-locomotion-framework_1705663992921\work\src\IK\tests\QPInverseKinematicsTest.cpp(979): FAILED:
  REQUIRE( toManifPose(kinDyn->getWorldTransform(desiredSetPoints.targetFrameDistance)) .translation() .norm() == Catch::Approx(desiredSetPoints.targetDistance).epsilon(tolerance) )
with expansion:
  76.8941567337 == Approx( 1.3854129089 )

===============================================================================
test cases:   5 |   4 passed | 1 failed
assertions: 661 | 660 passed | 1 failed

~~~

the same of https://github.com/ami-iit/bipedal-locomotion-framework/issues/799 .

**Comment by GiulioRomualdi** [comment]
Thanks to @traversaro https://github.com/ami-iit/bipedal-locomotion-framework/issues/800 fixes the issue, I can release a new version of the project and generate a new package from it so we don't need to add any patch

**Comment by traversaro** [comment]
> > Thanks to @traversaro [ami-iit/bipedal-locomotion-framework#800](https://github.com/ami-iit/bipedal-locomotion-framework/pull/800) fixes the issue, I can release a new version of the project and generate a new package from it so we don't need to add any patch
> 
> We can also just skip the test in the build script by passing -E to ctest.

Done in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/52/commits/448dd32683bdb85123784526fd34ce5b7cd21369 .

**Comment by traversaro** [comment]
Superseded by https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/53 .

**Pull request closed without merging**
