### PR TITLE
Add and fix python tests

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/issues/18 and add tests to avoid future regressions.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
`pytest` launched from the `bindings/python`  directory fails on two tests:
~~~
=========================== short test summary info ============================
FAILED python/ParametersHandler/tests/test_parameters_handler_toml.py::test_load_from_file - AssertionError: assert False == True
 +  where False = <bound method PyCapsule.set_from_file of \n>('config.toml')
 +    where <bound method PyCapsule.set_from_file of \n> = \n.set_from_file
FAILED python/ParametersHandler/tests/test_parameters_handler_yarp.py::test_load_from_file - AssertionError: assert False == True
 +  where False = <bound method PyCapsule.set_from_file_path of >('config.ini')
 +    where <bound method PyCapsule.set_from_file_path of > = .set_from_file_path
~~~
probably this is due to the fact that the tests assume that the current working directory is `bindings/python/ParametersHandler/tests` where config.ini and config.toml are contained. Anyhow, this is not a problem as we can skip the `test_load_from_file` tests.

**Comment by traversaro** [comment]
CI seems happy now.

**Comment by traversaro** [comment]
@GiulioRomualdi can we merge? So then we can also deal with conflicts in https://github.com/conda-forge/bipedal-locomotion-framework-feedstock/pull/17 .

**Review by GiulioRomualdi — APPROVED** [review]

**Comment by GiulioRomualdi** [comment]
I think we can wait for the CI and then you can merge it

**Pull request merged**
